name: "✨ Feature Request"
description: Suggest an idea for a new feature or enhancement for w1thermsensor
title: "[Feature]: "
labels: [feature request, triage]
assignees:
- timofurrer
body:

- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this feature request!
        
- type: textarea
  attributes:
    label: Description
    description: Please tell us about your feature idea.
    placeholder: Pitch your idea!
  validations:
    required: true
    
- type: checkboxes
  attributes:
    label: Guidelines
    description: Please notice our contribution guidelines
    options:
      - label: I have read the contributing guide lines at [CONTRIBUTING](https://github.com/timofurrer/w1thermsensor/blob/master/.github/CONTRIBUTING.md)
        required: true
      - label: I have read and respect the code of conduct at [Code of Conduct](https://github.com/timofurrer/w1thermsensor/blob/master/.github/CODE_OF_CONDUCT.md)
        required: true
      - label: "I have searched the existing issues and I'm convinced that mine is new"
        required: true

